### ISSUE TITLE
configure: error:  invalid package name: perl PERL

### ISSUE THREAD

**Issue by fleetside72** [theory/pgenv#15]
I'm running this in WSL, so maybe a long shot.
short-of-it: At the build step I get `configure: error:  invalid package name: perl PERL`
here is some bash output for my situation:

lsb_release -a
-------------------
```
pt@USHCC10091:~/.pgenv$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.5 LTS
Release:        16.04
Codename:       xenial
```

pgenv check
-------------------
```
pt@USHCC10091:~/.pgenv$ pgenv check
[OK] make:      /usr/bin/make
[OK] curl:      /usr/bin/curl
[OK] patch:     /usr/bin/patch
[OK] tar:       /bin/tar
[OK] sed:       /bin/sed
[OK] perl:      /usr/bin/perl
[OK] python:    /usr/bin/python
```

git clone contents
-------------------------------
```
pt@USHCC10091:~/.pgenv$ ls -lsa
total 24
 0 drwxrwxrwx 1 pt pt  4096 Sep 20 15:53 .
 0 drwxr-xr-x 1 pt pt  4096 Sep 20 15:56 ..
 0 drwxrwxrwx 1 pt pt  4096 Sep 20 15:27 bin
 0 drwxrwxrwx 1 pt pt  4096 Sep 20 15:27 .git
 0 -rw-rw-rw- 1 pt pt    23 Sep 20 15:27 .gitignore
 4 -rw-rw-rw- 1 pt pt  1081 Sep 20 15:27 LICENSE.md
 4 -rw-rw-rw- 1 pt pt  1180 Sep 20 15:53 .pgenv.conf
16 -rw-rw-rw- 1 pt pt 14809 Sep 20 15:27 README.md
 0 drwxrwxrwx 1 pt pt  4096 Sep 20 15:54 src
```
do the build
-------------------------
```
pt@USHCC10091:~/.pgenv$ pgenv build 10.5
configure: error: invalid package name: perl  PERL
```

check perl version
-----------------------------
```
pt@USHCC10091:~/.pgenv$ perl -v

This is perl 5, version 22, subversion 1 (v5.22.1) built for x86_64-linux-gnu-thread-multi
(with 69 registered patches, see perl -V for more detail)

Copyright 1987-2015, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.
```

**Comment by theory** [comment]
Thank you @fluca1978, mo betta now.

**Comment by fleetside72** [comment]
thanks so much

**Comment by theory** [comment]
Crap, no, that didn't work. Now I end up without perl compiled in, and the root directory is named `/Users/david/pg/pgsql-11beta4 --with-perl  PERL=/usr/bin/perl`, which is no good.

I spent some time trying to figure out how to make the `_OPTS` variables into arrays, instead (as suggested [here](https://stackoverflow.com/a/7454624/79202)), but was unable to find an effective way to serialize them in `pgenv_configuration_write_variable()` (`typeset` works only with global variables, while `typeset -p` outputs additional crap we don't want in the config file, I presume). More information [here](https://unix.stackexchange.com/a/137122).

At this point, I think we have to figure out some other way too get the quoting right. :-(

**Comment by fluca1978** [comment]
I get this working removing all quoting, I suspect it is something clashing with single quotes in the configuration file and the usage of double quoting in variable interpolation. I've build 11beta4 fine adding also some other flags in the configuration just to test `configure` was behaving well.
If works as expected, please close the issue.

**Comment by theory** [comment]
73d286b isn't merged into master, @fluca1978.

Meanwhile, I see other issues:

```
$ pgenv restart
/Users/david/pg/bin/pgenv: line 280: s/^pgsql-//: No such file or directory
pg_ctl: too many command-line arguments (first is "")
Try "pg_ctl --help" for more information.
$ pgenv stop      
/Users/david/pg/bin/pgenv: line 280: s/^pgsql-//: No such file or directory
pg_ctl: too many command-line arguments (first is "")
Try "pg_ctl --help" for more information.
$ pgenv version
/Users/david/pg/bin/pgenv: line 280: s/^pgsql-//: No such file or directory
```

**Comment by fluca1978** [comment]
Sorry, I've temperature and should not be wroking on this...
I've fixed the `pg_ctl` issue, at least is working fine on my system. Could you confirm?

**Comment by theory** [comment]
Oh, I guess I might've broken that one, sorry.

**Comment by theory** [comment]
Yes, looks like 73d286b  fixed it, thanks!
