### ISSUE TITLE
Split script

### ISSUE THREAD

**Issue by fluca1978** [theory/pgenv#23]
Now that the script is growing, should we move all the `pgenv_xxx` functions to a separted file to be sourced in the beginning of the script?
Advantages: the code of the script will shrink and be more readable.
Disadvantages: the code is moved across two files.

Thoughts?

**Comment by theory** [comment]
Sure? I'm all for code organization, just not familiar enough with Bash to know what the best practices are.

**Comment by fluca1978** [comment]
I'm not sure, I was thinking about it. I do believe that "hiding" some stuff in another source file could make the whole script more readable. Of course, the script itself is less than 1000 lines so it can grow a little more before it becomes unreadable.

**Comment by fluca1978** [comment]
I close this because I don't believe it is time yet to evaluate the script split.
