### ISSUE TITLE
"pgenv check" needs check gcc existence too?

### ISSUE THREAD

**Issue by marcelorauldiaz** [theory/pgenv#29]
checking for cc... no
configure: error: in `/home/marcelo/.pgenv/src/postgresql-10.5':
configure: error: no acceptable C compiler found in $PATH
See `config.log' for more details

**Comment by theory** [comment]
You need to install a compiler toolchain in order to build Postgres from source. For Debian, for example, run

    apt-get build-essential

Then try again.
