### ISSUE TITLE
No uuid-ossp extension

### ISSUE THREAD

**Issue by hooopo** [theory/pgenv#30]
```
create EXTENSION "uuid-ossp";
ERROR:  could not open extension control file "/Users/hooopo/.pgenv/pgsql-10.1/share/extension/uuid-ossp.control": No such file or directory
```

it seems no contrib module installed?

my pg version 10.1；max os majave

**Comment by fluca1978** [comment]
Not really true.
When you `build` the system does essentially a `make world` which results in:
`PostgreSQL, contrib, and documentation installation complete.`
and you can check it by adding another extension, as an example `pgcrypto`.

The problem with `uuid-ossp` is that it must be specuified at `configure` time: <https://www.postgresql.org/docs/10/uuid-ossp.html#id-1.11.7.54.5>
with the option
```
% configure --help
...
 --with-uuid=LIB         build contrib/uuid-ossp using LIB (bsd,e2fs,ossp)
  --with-ossp-uuid        obsolete spelling of --with-uuid=ossp

...
```

You can use `pgenv config` to specify configure flags and rebuild it again.
