### ISSUE TITLE
Multiple installations of the same database version

### ISSUE THREAD

**Issue by Ovid** [theory/pgenv#32]
It would be very nice to install the same version of PostgreSQL more than once. 

Workflow:

1. `pgenv build-duplicate 9.6.2` (creates a `9.6.2-v$version` if it's not the first one)
2. `pgenv alias veure 9.6.2-v$version` (#31)
3. `bin/setup/install-sqitch`
4. `sqitch deploy`
5. Run tests against the new database
6. While tests are running, go to step one to "pre-prepare" for another Jenkins run rather than waiting for the same database

This would likely require separate data directories to be really useful.

**Comment by fluca1978** [comment]
This can already be done with different `PGENV_ROOT` variables. Does this trick not suffice?

**Comment by Ovid** [comment]
I'm rather sick right now and my brain isn't working as well as it could be :)

If I use `PGENV_ROOT` to set a different directory but install the same database version, you're saying I do something like this?

```
PGENV_ROOT=~/.pgenv/versions/v2/9.6.2 pgenv build 9.6.2
PGENV_ROOT=~/.pgenv/versions/v2/9.6.2 pgenv use 9.6.2
```

**Comment by theory** [comment]
Should this issue be closed? Is PGENV_ROOT the proper solution?

**Comment by theory** [comment]
@Ovid did @fluca1978's suggestion solve the problem for you?

**Comment by fluca1978** [comment]
@Ovid did you have a chance to check if `PGENV_:ROOT` can fix the problem?

**Comment by Ovid** [comment]
My apologies. This is years ago and I completely forgot about this. I would suggest closing the ticket. My apologies for the delay.
