### ISSUE TITLE
Install postgis

### ISSUE THREAD

**Issue by gma2th** [theory/pgenv#33]
It would be nice if we could install extensions like postgis with pgenv. Is there any plan to do so?

**Comment by fluca1978** [comment]
So far there is nothing I'm aware of.
It would be possible, but that requires
- starting an instance
- executing a script or something to install an extension

So far, I would add an option to `run-on-first-start` way of running a custom script, but I'm not convinced it is worth the effort.
Suggestions?

**Comment by fluca1978** [comment]
I'm closing this issue since it has been implemented a rough way to support custom scripts that can be used to install other pieces. Please open a new ticket in the case it does not suffice to your aim.
