### ISSUE TITLE
psql_history escape sequences

### ISSUE THREAD

**Issue by gma2th** [theory/pgenv#34]
```
$ psql
~> select 1 ;
┌──────────┐
│ ?column? │
╞══════════╡
│        1 │
└──────────┘
(1 row)

Time: 0.752 ms
~> \q

~
$ cat ~/.psql_history
_HiStOrY_V2_
select\0401\040;
\134q
```

**Comment by fluca1978** [comment]
Do you have any terminal specific setting? What if your run `psql -X`?

**Comment by gma2th** [comment]
I have no terminal specific settings, I have the same issue with `psql -X`. I'm on OSX.

**Comment by fluca1978** [comment]
Well, borders are not ASCII, and I see you have also timing enabled, that sounds to me there's a `.psqlrc` lying around, but if you have the same behavior with `psql -X` there must be something else going wrong here.
I suspect this is not a pgenv related issue, have you another database (not pgenv) to test against?
Of course, cleaning the history before each trial.

**Comment by gma2th** [comment]
I don't have the issue when I use PostgreSQL installed with brew.

**Comment by fluca1978** [comment]
I cannot reproduce the issue on Linux using 12.0.
I do confirm it seems you have
```
\pset linestyle unicode
\pset border 2
\pset unicode_header_linestyle double
```

so somewhere there must be something that is aliasing your `psql` or a `.psqlrc` file loaded.
Should be tested by other people with an OSX.

**Comment by gma2th** [comment]
Fixed it with
```
$ export LDFLAGS="-L/usr/local/opt/readline/lib -L/usr/local/opt/openssl/lib"
$ export CPPFLAGS="-I/usr/local/opt/readline/include -I/usr/local/opt/openssl/include"
```
before runing `pgenv build`.
https://github.com/Homebrew/legacy-homebrew/issues/45405#issuecomment-154182029

**Comment by fluca1978** [comment]
Great!
