### ISSUE TITLE
Installing extensions such as Postgis and PGRouting

### ISSUE THREAD

**Issue by Ovid** [theory/pgenv#40]
We have a product where our production environment uses Docker and has no issue with installing things like [postgis](https://postgis.net/) and [pgrouting](https://pgrouting.org/).

However, we have multiple remote developers and many of them (including me) are using pgenv for our PostgreSQL install and I don't know how to get those extensions installed properly. The error looks like this:

    acme_test=# create extension if not exists postgis;
    ERROR:  could not open extension control file "/home/ovid/.pgenv/pgsql-11.5/share/extension/postgis.control": No such file or directory

I have several `postgis.control` files, but I don't know how to link them (or if it's safe to do so):

    12:11:34 {spike-pgrouting-120} ~/client/acme-api $ locate postgis.control
    /etc/alternatives/postgresql-12-postgis.control
    /usr/share/postgresql/12/extension/postgis.control
    /var/lib/dpkg/alternatives/postgresql-12-postgis.control

I've installed postgis via `sudo apt-get install postgis`. 

This is Postgresql 11.5 on Ubuntu 18.04.4.

**Comment by gma2th** [comment]
You need to compile postgis from the source using with the correct configure settings:
```
tar xvzf postgis-3.0.1.tar.gz
cd postgis-3.0.1
eval ./configure $(pg_config --configure)/
make
make install
```
https://postgis.net/source/

pgenv bin must be in your path:
```
export PATH="$HOME/.pgenv/bin:$HOME/.pgenv/pgsql/bin:$PATH"'
```

See:
https://github.com/theory/pgenv/pull/35
https://github.com/theory/pgenv/issues/33
