### ISSUE TITLE
Tag releases?

### ISSUE THREAD

**Issue by fluca1978** [theory/pgenv#44]
We should start to tag version releases? In the case, what versioning schema should we adopt?

**Comment by theory** [comment]
Right. I’m thinking semantic versions. Should we just start with v1.0.0?

**Comment by fluca1978** [comment]
Sorry for late replying, but I'm having some hard times.
I have no particular opinion about the versioning schema and the starting number, so it's fine for me `1.0.0`.
Before tagging as a release, any idea about how to incliude such information into the script itself? A local variable to display in the `help` or and hardcoded string?

**Comment by theory** [comment]
A variable sounds good to me.

Hope you're doing better, @fluca1978. These are super trying times, it's super important to care for you and yours.

**Comment by fluca1978** [comment]
Released version 1.0.0 with an internal variable.
