### ISSUE TITLE
Support multiple CFLAGS in PGENV_CONFIGURE_OPTS

### ISSUE THREAD

**Issue by hanefi** [theory/pgenv#45]
I want to add multiple `CFLAGS` to my configure options. However I failed to find a reasonable way to place it in my `.pgenv.default.conf` file.

Currently I have the following line in `.pgenv.default.conf`

    PGENV_CONFIGURE_OPTS='--enable-cassert --enable-depend --enable-debug --with-icu --with-libxml --with-libxslt --with-openssl --with-uuid=e2fs'

I also want to set CFLAGS but pgenv fails to parse my PGENV_CONFIGURE_OPTS values such as:

    PGENV_CONFIGURE_OPTS='--enable-cassert --enable-depend --enable-debug --with-icu --with-libxml --with-libxslt --with-openssl --with-uuid=e2fs CFLAGS="-Og -g3 -fno-omit-frame-pointer -gdwarf"'

How do you recommend I escape the whitespaces properly?

--------------

My current workaround is setting the CFLAGS on bash, and lose track of those flags later as they are not stored in any files. For example:

    bash$ CFLAGS="-Og -g3 -fno-omit-frame-pointer -gdwarf"  pgenv rebuild 11.10

**Comment by fluca1978** [comment]
I'm not sure this is a `pgenv` related problem.
The fact is that `configure` is going to be instrumented by CFLAGS, but such variable is not specified on the command line, rather within the environment.
Therefore the only way I can see is to **`export CFLAGS="-Og -g3 -fno-omit-frame-pointer -gdwarf"`**.

Of course, you are going to loose those flags as you will in any manual `configure` way.

If we need to store CFLAGS we need to provide a particular `PGENV_CFLAGS` like configuration variable and use it appropriately. 
Can you explain why it is so important to keep those flags?

**Comment by theory** [comment]
I ran into this issue and have attempted a fix in #48.
