### ISSUE TITLE
Move configuration file(s) to ~/.config folder?

### ISSUE THREAD

**Issue by fluca1978** [theory/pgenv#50]
This is partially related to #47 and the work done in #49.
So far, the configuration files are stoed in `PGENV_ROOT`, while it could be easy enough to migrate them to ``/.config`, that is where a user should keep her own configuration.
Advantages:
- configuration files will be kept as part of the home folder, thus she can backup and migrate to other machines with external tools;
- separating `PGENV_ROOT` from its configuration should prevent accidental removal of configuration by the user;
- multiple `pgenv` instances can share the very same configuration.

Drawbacks:
- the user will have to manually delete `PGENV_ROOT` and the configuration folder/files if she does not want `pgenv` anymore.

I could work on this in the case it is interesting.

**Comment by theory** [comment]
I think `$PGENV_ROOT/config` makes a lot of sense. `~/.config` less so (I have work files in that directory, in fact!). This way all the config files are separate from the root of the project and the files, just bundled amongst themselves, but still all in PGENV_ROOT where they can all be cleaned up at once.

**Comment by fluca1978** [comment]
What about making a kind of double choice? If there is the configuration file under `~/.config` use that, otherwise look for `PGENV_ROOT/` configuration file?

Also, you are proposing to move `.pgenvxxx.conf` files to `PGENV_ROOT/config`, that is not exactly what I meant.
In preparing a new computer, having them under `~/.config` probably would have solved the problem reported in #47, at least if you have such directory under backup/source control.

No pressure at all on this, just a proposal.

**Comment by theory** [comment]
Yes, I was suggesting that *all* of the configuration files go into their own directory. I like that idea.

**Comment by fluca1978** [comment]
Closed by 4d96c333f5ccbc041f3b50c8022809860b571584
