### ISSUE TITLE
pg_hba.conf & postgresql.conf

### ISSUE THREAD

**Issue by bmyers28** [theory/pgenv#59]
Hello... I just started using pgenv as a database server that I have various different versions of postgres built so I can change between them, and restore version specific database backups.  The problem is that our backups don't contain the pg_hba.conf or the postgresql.conf so I have to make sure I have copies of those two config files in the base pgsql-## and then copy them into the data directory after I have extracted the backup.  

Is there a way to tell pgenv to look for these 2 specific files in a different location that I can keep static?  If not is it possible to add this as an enhancement.    If there are other required configuration files for postgres to initialize correctly then probably include those as well.  

Thanks in advance for any assistance!

**Comment by fluca1978** [comment]
You can use the capability of PostgreSQL to start with different and custom file locations (see <https://www.postgresql.org/docs/14/runtime-config-file-locations.html>), and then configure your own `pgenv` instances to use a `PGENV_START_OPTIONS` accordingly.
