### ISSUE TITLE
Instrument the creation of the configuration file

### ISSUE THREAD

**Issue by fluca1978** [theory/pgenv#62]
`pgenv` creates a new *per-PostrgeSQL* configuration file as soon as it builds/rebuilds the version.
When a PostgreSQL version is used/started, `pgenv` looks for the per-version configuration file and if found loads it, or it loads the file as pointed out from the environment variable `PGENV_CONFIGURATION_FILE` (see #61).
It could be useful to prevent at all `pgenv` form creating per-version configuration files, for example if the user wants to use always a specific configuration file and does not care about having unused files laying around (see discussion <https://github.com/theory/pgenv/pull/61#issuecomment-1676141013>).

The behavior can be achieved in different ways:
- use an environment variable, for example `PGENV_AUTOWRITE_CONFIGURATION_FILE` set to `yes` or `no` to instrument the application;
- use separate subcommand, for example `build` and `build-no-config` to distinguish about the behavior
- use some sort of command line option, lie for instance `pgenv build --no-config`, that will require to be able to correctly parse the command line, for example with `getopt`.

The first approach is the simplest one, while the last is the more extensible and can give us room to implement other options and improve commands, that so far accepts only positional arguments. For example, the latter approach could also allow the user to specify the configuration file to use on a per-command basis, like `pgenv build 16beta --with-config /path/to/config` instead of using the `PGENV_CONFIGURATION_FILE` variable.

I am towards the `getopt` like approach, also to avoid adding other environment variables. Clearly, this approach requires  a quite extensive command line refactoring.

**Comment by theory** [comment]
I like both an option and an environment variable, mostly because I will forget the option but can put the variable in my `default.conf` and forget about it. The option ought to override that variable, though, so a `--with-config` to counter it might be handy. My $2.

**Comment by fluca1978** [comment]
@theory #63 is an initial work on using `getopt` to parse the command line options. In particular, `--config-file-write no` does what this issue requires.

Despite this, I believe that having `getopt` in the way can make a lot more robust the command line, for example: `pgenv --version 16 start` could understand the need to `switch` and `start` the appropriated version (and stop another one if running). Could it be worth?

**Comment by fluca1978** [comment]
@theory please see #64 that is a pull request because it breaks backward compatibility.
