### ISSUE TITLE
Support for pgadmin installation through pgenv

### ISSUE THREAD

**Issue by briansalehi** [theory/pgenv#66]
I'm using a specific Linux distro where I don't have the chance to setup pgadmin through package manager, pacman.
Besides, I feel setting up pgadmin is a pain on the neck. What do you think of adding an option for installation of pgadmin?
This setup process can be as simple as downloading the latest version.
I would really like to know what everybody thinks about this feature.

**Comment by theory** [comment]
I like that pgenv is very focused on one thing: building and managing different versions of Postgres. Also managing pgAdmin sounds like a whole 'nother thing. What do you think, @fluca1978?

**Comment by fluca1978** [comment]
I personally don't think this is useful. I don't use pgadmin, and if I remember correctly, it needs python (hence a pythonenv), so a lot of external dependencies to track. Moreover, people could not like the way we install thru `pgenv` (e.g., we install by latest sources, but people would want a distro package).
While I like the idea that `pgenv` should be able to do more and more stuff, I don't think pgadmin is appropriate.

**Comment by briansalehi** [comment]
Both views are convincing. pgenv should only do one thing and do it well, while this feature plays totally on a different league. Even if we could make it, it should have been on a different script. And these two scripts should have had the same interface which is a pain to keep two scripts in sync in my experience.

The dependencies are also a problem for sure.
But may I ask if you're not using pgAdmin, then what are you using?

**Comment by fluca1978** [comment]
> Both views are convincing. pgenv should only do one thing and do it well, while this feature plays totally on a different league. Even if we could make it, it should have been on a different script. And these two scripts should have had the same interface which is a pain to keep two scripts in sync in my experience.
> 

One possible solution should be to work on *pgenv extensions*, something like: `pgenv runx pgadmin` where the arguments to `runx` (or whatever we would call it) is a third party script to run. Therefore, `pgadmin` could be a scrupt that installs pgadmin, and `pgenv` will totally pass over another script the control via `runx`.
Doing this would allow us to distribute and include scripts that can bend pgenv to do whatever the user needs. The point then is: are we going to maintain such scripts?

>  But may I ask if you're not using pgAdmin, then what are you using?

I'm a kind of text-only guy, with a simple approach: `psql` everywhere (and Emacs to edit long pieces of code).

**Comment by theory** [comment]
> I'm a kind of text-only guy, with a simple approach: `psql` everywhere (and Emacs to edit long pieces of code).

Same.

**Comment by briansalehi** [comment]
Well, it feels great to see professionals are CLI users because I was just starting to learn postgres and I was wondering if the not so intuitive pgAdmin4 GUI is the only way to work with the postgres professionally. Hopefully it's not, so I'm going to use psql too. Thanks for clarifying this to me, it feels home when working on terminal.

I'm going to close this issue and leave it.
