### ISSUE TITLE
Trying building 1st version available 1.08

### ISSUE THREAD

**Issue by PauloLaScience** [theory/pgenv#68]
```bash
paul@6Z7T2D3  ~  export PGENV_DEBUG=1
paul@6Z7T2D3  ~  pgenv build 1.08
[DEBUG] Looking for configuration in /home/paul/.pgenv/config/1.08.conf
[DEBUG] Looking for configuration in /home/paul/.pgenv/config/default.conf
[DEBUG] Load configuration from [/home/paul/.pgenv/config/default.conf]
[DEBUG] Downloading tarball
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   146    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
paul@6Z7T2D3  ~  
```
This is 'pgenv' version 1.3.3 [70af4d4]

I check on site https://ftp.postgresql.org/pub/source/ and v1.08 directory exist

Best regards
PaulemPG

**Comment by theory** [comment]
Probably because the file was named [postgres95-1.08.tar.gz](https://ftp.postgresql.org/pub/source/v1.08/postgres95-1.08.tar.gz) and `pgenv` expects it to be named `postgresql-$version`. [v6](https://ftp.postgresql.org/pub/source/v6.0/) is probably the oldest version with that name.

I think we should probably remove 1.x from the list of available versions. And maybe 6.x, too.

**Comment by PauloLaScience** [comment]
It makes sense to keep only working version.De : David E. Wheeler ***@***.***>Envoyé : samedi, février 24, 2024 8:45:13 PMÀ : theory/pgenv ***@***.***>Cc : @PaulemPG ***@***.***>; Author ***@***.***>Objet : Re: [theory/pgenv] Trying building 1st version available 1.08 (Issue #68)
Probably because the file was named postgres95-1.08.tar.gz and pgenv expects it to be named postgresql-$version. v6 is probably the oldest version with that name.
I think we should probably remove 1.x from the list of available versions. And maybe 6.x, too.

**Comment by fluca1978** [comment]
Either remove versions prior to `7` or change the download path for such versions.
In any case, I suspect users won't be able to build such an old version in an automated way.

**Comment by fluca1978** [comment]
@PauloLaScience and @theory  could you give a try at #69 ? I've tested that `pgenv` cannot use any <= 6 version, and it seems fine to me.

**Comment by thanodnl** [comment]
Since this merge the `ues`/`switch` command seem to fail:

```bash
$ pgenv use 15.5
/home/vscode/.pgenv/bin/pgenv: line 395: s/\([[:digit:]]\{1,2\}\).*/\1/: No such file or directory
```

I haven't looked deep into the cause, simply did a quick bisect to find it was this change that caused it to fail now.
