### ISSUE TITLE
Replace [KO] with [NO] and more verbose message for missing dependencies

### ISSUE THREAD

**Issue by briansalehi** [theory/pgenv#76]
I just migrated from Arch to Fedora and there were missing packages on my fresh system. When I tried to start my db, pgenv complained [KO] patch. Well, I was confused! What is a KO? Well, I recalled that we have a `check` command but this was only because I already contributed and had an idea of all the existing commands, but still it took me a few minutes to figure that out. I simply suggest to replace [KO] with [NO] because [KO] only makes sense when seen in the list of many [OK]s. But when shown alone it's confusing.

`[KO] patch:     NOT found!`

will be:

`[NO] required tool 'patch' could not be found.`

More verbosity never hurts, what's your ideas?

**Comment by fluca1978** [comment]
I have no particular opinion on this, since `KO` seems fine to me to indicate that *there is a problem and the application cannot conitnue*.
We could change the `: NOT found!` message to something clearer like `: required but NOT found!` to keep the name of the tool on the leftmost part of the error message.

@theory what do you think about?

**Comment by briansalehi** [comment]
I have to admit this is a better idea to keep the tool name on the left and applying this minor change to the message. The message looked like an internal error to me but additional detail makes it less misleading.
About the KO, honestly I'm not sure if it naturally comes as the opposite of OK to English speaking minds, but it didn't for me :) But it doesn't seem like a huge deal if the message explains more.

**Comment by theory** [comment]
I think making the error message clearer can only help things. `patch:     NOT found!` confuses me. Does it mean a patch wasn't found? What patch? That's how I would have read it, rather than the `patch` utility is missing.

Don't love "KO", because it's not the opposite of "OK" in English; typically it means "Knockout", in a boxing context. I'd prefer "NO" or, even better, "ERR".

**Comment by briansalehi** [comment]
Okay I just tried a few substitutions for [OK] and [KO], then I realized [FOUND] and [ERROR] combination looks even more clear!

```
pgenv check

Using PGENV_ROOT /home/brian/.local
[FOUND] make:   /usr/bin/make
[FOUND] curl:   /usr/bin/curl
[FOUND] tar:    /usr/bin/tar
[FOUND] sed:    /usr/bin/sed
[FOUND] sort:   /usr/bin/sort
[FOUND] tr:     /usr/bin/tr
[FOUND] tail:   /usr/bin/tail
[ERROR] patch   required but NOT found!
```

This cannot be misinterpreted!
They will be aligned with a mono font which I guess most terminal users have it anyways.
It is specially clear when a missing tool is found by running a command other than `check`:

```
pgenv build

Using PGENV_ROOT /home/brian/.local
[ERROR] patch   required but NOT found!
```

What do you think? @theory @fluca1978

**Comment by briansalehi** [comment]
Also removing colon in case the utility is missing makes sense.

**Comment by fluca1978** [comment]
> Also removing colon in case the utility is missing makes sense.

I was just starting to write that I like the colon, or better, please format every message in the same way. Having a colon makes me thing that I can use a regular expression to quickly catch and interpret the message, even if I'm not going to do in here...

**Comment by briansalehi** [comment]
I see, a colon would make text processing easier. Of course the second column should have a consistent format in that sense, either no colon at all or to have it for all. 
For me, having a colon looks better than not having a colon at all, as it separates tool name from description. Okay I'll bring it back and push again.
